app/finances/urls.py
from django.urls import path
from finances.views import (MovementCreateView, MovementUpdateView, MovementDeleteView,
                            MovementMontArchiveView,MovementLastMonth ,MovementAdminListView,
                            WorkersTimeListView, AttendanceReport, AttendanceReportFormClass,
                            AttendaceFullReportClass, UserAccountingTemplateView,
                            ProjectAttendanceReport)

app_name = 'finances'

urlpatterns = [
    path('', MovementCreateView.as_view(), name = 'finances_home'),
    path('currentmonth',MovementLastMonth.as_view(), name='finances_lastmonth'),
    path('movementlist/<int:year>/<int:month>', MovementMontArchiveView.as_view(), name='finances_month'),
    path('movementresume', UserAccountingTemplateView.as_view(), name='finances_resume'),
    path('edit/<int:pk>', MovementUpdateView.as_view(), name = 'finances_edit'),
    path('delete/<int:pk>', MovementDeleteView.as_view(), name='finances_delete'),
    path('workerstime', WorkersTimeListView.as_view(), name='workerstime_list'),
    #path('attendance', AttendanceReport.as_view(), name='attendance_report'),
    path(
        'attendance/<str:inicio>/<str:final>/<str:extra>/<str:adicional>',
        AttendaceFullReportClass.as_view(),
        name='attendance_report'),
    path('attendanceform', AttendanceReportFormClass.as_view(), name='attendance_form'),
    path(
        'projectattendance/<int:pk>',
        ProjectAttendanceReport.as_view(),
        name='projectattendance_report'
    ),
]

app/inxcontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('inxcontrol/admin/', admin.site.urls),
    path('inxcontrol/profiles/', include('profiles.urls'), name='profiles'),
    path('inxcontrol/finances/', include('finances.urls'), name='finances'),
    path('inxcontrol/projects/', include('projects.urls'), name='projects'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

app/profiles/urls.py
from django.urls import path, include
from .views import (UserCreateView, UserListView, UserDetailView, UserUpdateView,
                    SupplierListView, SupplierDetailView,SupplierCreateView, SupplierUpdateView,
                    ClientListView, ClientDetailView,ClientCreateView, ClientUpdateView, 
                    ClientContactUpdateView, ClientContactCreateView,  ClientContactDetailView, ClientContactListView,
                    SupplierContactUpdateView, SupplierContactCreateView,  SupplierContactDetailView, SupplierContactListView,
                    WorkerCreateView, WorkerTimeCreateView, WorkerTimeUpdateView, WorkerTimeWeekArchiveView,
                    WorkerTimeLastWeek, WorkerCostCreateView, WorkerCostUpdateView)

from django.contrib.auth.views import LoginView

app_name = 'profiles'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('usercreate', UserCreateView.as_view(), name='user_create'),
    path('userlist', UserListView.as_view(), name='user_list'),
    path('login', LoginView.as_view(), name='user_login'),
    path('detail/<int:pk>', UserDetailView.as_view(), name = 'user_detail'),
    path('userupdate/<int:pk>', UserUpdateView.as_view(), name='user_update'),
    path('workercreate', WorkerCreateView.as_view(), name = 'worker_create'),
    path('workertimecreate', WorkerTimeCreateView.as_view(), name='workertime_create'),
    path('workertimeupdate/<int:pk>', WorkerTimeUpdateView.as_view(), name='workertime_update'),
    path('workertime/<int:year>/week/<int:week>', WorkerTimeWeekArchiveView.as_view(), name='workertime_week'),
    path('workertime/last', WorkerTimeLastWeek.as_view(), name='workertime_lastweek'),
    path('workercostcreate/<int:pk>', WorkerCostCreateView.as_view(), name='workercost_create'),
    path('workercostupdate/<int:pk>', WorkerCostUpdateView.as_view(), name='workercost_update'),
    path('clientcreate', ClientCreateView.as_view(), name='client_create'),
    path('clientlist', ClientListView.as_view(), name = 'client_list'),
    path('clientdetail/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('clientupdate/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('suppliercreate', SupplierCreateView.as_view(), name='supplier_create'),
    path('supplierlist', SupplierListView.as_view(), name='supplier_list'),
    path('supplierdetail/<int:pk>', SupplierDetailView.as_view(), name='supplier_detail'),
    path('supplierupdate/<int:pk>', SupplierUpdateView.as_view(), name='supplier_update'),
    path('clientcontactcreate', ClientContactCreateView.as_view(), name='clientcontact_create'),
    path('clientcontactlist', ClientContactListView.as_view(), name = 'clientcontact_list'),
    path('clientcontactdetail/<int:pk>', ClientContactDetailView.as_view(), name='clientcontact_detail'),
    path('clientcontactupdate/<int:pk>', ClientContactUpdateView.as_view(), name='clientcontact_update'),
    path('suppliercontactcreate', SupplierContactCreateView.as_view(), name='suppliercontact_create'),
    path('suppliercontactlist', SupplierContactListView.as_view(), name = 'suppliercontact_list'),
    path('suppliercontactdetail/<int:pk>', SupplierContactDetailView.as_view(), name='suppliercontact_detail'),
    path('suppliercontactupdate/<int:pk>', SupplierContactUpdateView.as_view(), name='suppliercontact_update'),
]

app/projects/urls.py
from django.urls import path

from .views import ( ProjectCreateView, ProjectListView, ProjectDetailView,
                     ProjectUpdateView, ActivityCreateView, ActivityDetailView,
                     ActivityListView, RequirementCreateView, RequirementListView,
                     ReportCreateView, ReportListView, ReportUpdateView, ActivityUpdateView,
                     ReportDetailView, PhotoCreateView, RequirementUpdateView,
                     ActivityDeleteView, ActivityCompactListView, ReportCardListView,
                     ActivityProgressCreateView, ReportProgressCreateView,
                     ActivityProgressUpdateView, ReportProgressUpdateView,
                     ReportProgressDeleteView, ActivityProgressDeleteView, SearchListView,
                     ReportDeleteView, ReportDayArchiveView, ReportLastdayArchiveView,
                     ActivityPrintView, RequirementCompleteView )
app_name = 'projects'

urlpatterns = [
    path('projectlist', ProjectListView.as_view(), name='project_list' ),
    path('projectcreate', ProjectCreateView.as_view(),name='project_create'),
    path("projectdetail/<int:pk>", ProjectDetailView.as_view(), name = 'project_detail'),
    path('projectupdate/<int:pk>', ProjectUpdateView.as_view(), name='project_update' ),
    path('activitylist', ActivityListView.as_view(), name='activity_list'),
    path('activityprint', ActivityPrintView.as_view(), name='activity_print'),
    path('activitycompactlist', ActivityCompactListView.as_view(), name='activity_compactlist'),
    path('activitycreate', ActivityCreateView.as_view(), name='activity_create'),
    path('activitydetail/<int:pk>', ActivityDetailView.as_view(), name='activity_detail'),
    path('activityupdate/<int:pk>', ActivityUpdateView.as_view(), name='activity_update'),
    path('activitydelete/<int:pk>', ActivityDeleteView.as_view(), name='activity_delete'),
    path('activityprogresscreate/<int:pk>', ActivityProgressCreateView.as_view(), name='activityprogress_create'),
    path('activityprogressupdate/<int:pk>', ActivityProgressUpdateView.as_view(), name='activityprogress_update'),
    path('activityprogressdelete/<int:pk>', ActivityProgressDeleteView.as_view(), name='activityprogress_delete'),
    path('requirementcreate', RequirementCreateView.as_view(), name='requirement_create'),
    path('requirementupdate/<int:pk>', RequirementUpdateView.as_view(), name='requirement_update'),
    path('requirementlist', RequirementListView.as_view(), name='requirement_list'),
    path('requirementcomplete/<int:pk>', RequirementCompleteView.as_view(), name='requirement_complete'),
    path('reportlist', ReportListView.as_view(), name='report_list'),
    path('reports/lastday', ReportLastdayArchiveView.as_view(), name='report_lastday'),
    path('reports/<int:year>/<str:month>/<int:day>/', ReportDayArchiveView.as_view(), name='report_dayarchive'),
    path('reportcardlist', ReportCardListView.as_view(), name='report_cardlist'),
    path('reportcreate', ReportCreateView.as_view(), name='report_create'),
    path('reportcreate/<int:pk>', ReportProgressCreateView.as_view(), name='report2_create'),
    path('reportdelete/<int:pk>', ReportDeleteView.as_view(), name='report_delete'),
    path('reportprogressupdate/<int:pk>', ReportProgressUpdateView.as_view(), name='reportprogress_update'),
    path('reportprogresdelete/<int:pk>', ReportProgressDeleteView.as_view(), name='reportprogress_delete'),
    path('reportupdate/<int:pk>', ReportUpdateView.as_view(), name='report_update'),
    path('reportdetail/<int:pk>', PhotoCreateView.as_view(), name='report_detail'),
    path('search', SearchListView.as_view(), name='all_search'),
]

app/finances/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Supplier
from datetime import datetime

import os

class Movement(models.Model):
    payee = models.ForeignKey(
        Supplier,
        models.SET_NULL,
        blank = True,
        null = True
    )
    creation_date = models.DateField(
        default = datetime.now,
    )
    description = models.CharField(
        max_length=254
    )
    amount = models.DecimalField(
        decimal_places=3,
        max_digits=7
    )
    no_invoice = models.BooleanField(
        blank = True,
        default = False
    )
    payment = models.BooleanField(
        blank = True,
        default = False
    )
    responsable = models.ForeignKey(
        User,
        models.CASCADE
    )
    files = models.FileField(
        upload_to="finances/%Y/%m/%d/",
        blank = True,
        null = True
    )

app/inxcontrol/templates/__base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS CUSTOM -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <title>inxcontrol | {% block title %}{% endblock %}</title>
</head>

<body>
    <div class="header">
        <h3>INX-CONTROL</h3>
    </div>

{% block content %}
{% endblock %}

<div class="footer">
    <div class="sitemap">
        <div>
            <h5>
                Mapa del sitio
            </h5>
            <ul>
                <li><h4>Perfiles</h4></li>
                <li><a href="{% url 'profiles:user_list' %}">Usuarios</a></li>
                <li><a href="{% url 'profiles:client_list' %}">Clientes</a></li>
                <li><a href="{% url 'profiles:supplier_list' %}">Proveedores</a></li>
                <li><a href="{% url 'profiles:workertime_lastweek' %}">Control de tiempo</a></li>
            </ul>
            <ul>
                <li><h4>Finanzas</h4></li>
                <li><a href="{% url 'finances:finances_home' %}">Movimientos</a></li>
                {% if perms.finances.change_movement %}
                <li><a href="{% url 'finances:finances_resume' %}">Resumen</a></li>
                <li><a href="{% url 'finances:attendance_form' %}">Asistencia</a></li>
                <li><a href="{% url 'finances:workerstime_list' %}">Horas-proyecto</a></li> 
                {% endif %}
            </ul>
            <ul>
                <li><h4>Proyectos</h4></li>
                <li><a href="{% url 'projects:project_list' %}">Proyectos</a></li>
                <li><a href="{% url 'projects:activity_list' %}">Actividades</a></li>
                <li><a href="{% url 'projects:requirement_list' %}?status=0">Requerimientos</a></li>
                <li><a href="{% url 'projects:report_list' %}">Reportes</a></li>
                <li><a class="button" href="{% url 'projects:report_create' %}">Nuevo Reporte</a></li>
            </ul>
        </div>
        <form method=POST action={% url 'projects:all_search' %}>
            {% csrf_token %}
            <input
            type="search"
            placeholder="Buscar"
            aria-label="Search"
            name="valuesearch">
            <button type="submit">Buscar</button>
        </form>
    </div>
</div>

</body>

app/inxcontrol/templates/common_menu.html
{{ svg_icon }}

app/inxcontrol/templates/search_results.html
{% extends '__base.html' %}

{% block title %}
    Resultados
{% endblock title %}

{% block content %}
{% load static %}
<h3>Resultados</h3>
<p>Resultados para "{{ searched }}"
<h5>Proyectos (en el nombre):</h5>
<div class="searchlist">
<ul>
{% for project in projects %}
<li>
    <a href="{% url 'projects:project_detail' project.pk %}">
        <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
    {{ project.name }}
</li>
{% endfor %}
</ul>

<h5>Actividades (en el nombre):</h5>
<ul>
{% for activity in activities %}
<li>
    <a href="{% url 'projects:activity_detail' activity.pk %}">
        <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
    {{ activity.name }}
</li>
{% endfor %}
</ul>

<h5>Reportes (en descripcion):</h5>
<ul>
{% for report in reports %}
<li>
    <a href="{% url 'projects:report_detail' report.pk %}">
        <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
    {{ report.name }}
</li>
{% endfor %}
</ul>
</div>
{% endblock content %}