app/finances/urls.py
from django.urls import path
from finances.views import (MovementCreateView, MovementUpdateView, MovementDeleteView,
                            MovementMontArchiveView,MovementLastMonth ,MovementAdminListView,
                            WorkersTimeListView, AttendanceReport, AttendanceReportFormClass,
                            AttendaceFullReportClass, UserAccountingTemplateView,
                            ProjectAttendanceReport)

app_name = 'finances'

urlpatterns = [
    path('', MovementCreateView.as_view(), name = 'finances_home'),
    path('currentmonth',MovementLastMonth.as_view(), name='finances_lastmonth'),
    path('movementlist/<int:year>/<int:month>', MovementMontArchiveView.as_view(), name='finances_month'),
    path('movementresume', UserAccountingTemplateView.as_view(), name='finances_resume'),
    path('edit/<int:pk>', MovementUpdateView.as_view(), name = 'finances_edit'),
    path('delete/<int:pk>', MovementDeleteView.as_view(), name='finances_delete'),
    path('workerstime', WorkersTimeListView.as_view(), name='workerstime_list'),
    #path('attendance', AttendanceReport.as_view(), name='attendance_report'),
    path(
        'attendance/<str:inicio>/<str:final>/<str:extra>/<str:adicional>',
        AttendaceFullReportClass.as_view(),
        name='attendance_report'),
    path('attendanceform', AttendanceReportFormClass.as_view(), name='attendance_form'),
    path(
        'projectattendance/<int:pk>',
        ProjectAttendanceReport.as_view(),
        name='projectattendance_report'
    ),
]

app/inxcontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('inxcontrol/admin/', admin.site.urls),
    path('inxcontrol/profiles/', include('profiles.urls'), name='profiles'),
    path('inxcontrol/finances/', include('finances.urls'), name='finances'),
    path('inxcontrol/projects/', include('projects.urls'), name='projects'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

app/finances/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Supplier
from datetime import datetime

import os

class Movement(models.Model):
    payee = models.ForeignKey(
        Supplier,
        models.SET_NULL,
        blank = True,
        null = True
    )
    creation_date = models.DateField(
        default = datetime.now,
    )
    description = models.CharField(
        max_length=254
    )
    amount = models.DecimalField(
        decimal_places=3,
        max_digits=7
    )
    no_invoice = models.BooleanField(
        blank = True,
        default = False
    )
    payment = models.BooleanField(
        blank = True,
        default = False
    )
    responsable = models.ForeignKey(
        User,
        models.CASCADE
    )
    files = models.FileField(
        upload_to="finances/%Y/%m/%d/",
        blank = True,
        null = True
    )

app/finances/forms.py
from django import forms
from django.forms import ModelChoiceField
from django.contrib.auth.models import User
from profiles.models import Supplier
from datetime import datetime
from finances.models import Movement

class UserModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.get_full_name()

class MovementCreateForm(forms.ModelForm):
    responsable = UserModelChoiceField(
        queryset=User.objects.filter(is_active=True),
        widget = forms.Select(),
        label = 'Responsable',
    )
    class Meta:
        model = Movement
        fields = '__all__'
        widgets = {
            'payee':forms.Select(attrs={'class':'form-control'}),
            'creation_date':forms.DateInput(attrs={'class':'form-control datepicker','type':'date'}),
            'description':forms.Textarea(),
            'amount':forms.NumberInput(attrs={'class':'form-control'}),
            'no_invoice':forms.CheckboxInput(attrs={'class':'form-control'}),
            'payment':forms.CheckboxInput(attrs={'class':'form-control'}),
            'responsable':forms.Select(),
            'files':forms.FileInput(attrs={}),
        }
        labels = {
            'payee':'Proveedor',
            'creation_date':'Fecha de compra',
            'description':'Descripción',
            'amount':'Monto',
            'no_invoice':'Sin factura',
            'payment':'Pagado',
            'files':'Factura',
        }

class DateSelectForm(forms.Form):
    init_date = forms.CharField(
        label = 'Fecha de inicio: ',
        widget = forms.DateInput(attrs={'class':'form-control datepicker','type':'date'})
    )
    end_date = forms.CharField(
        label = 'Fecha final: ',
        widget = forms.DateInput(attrs={'class':'form-control datepicker','type':'date'})
    )
    
class AttendanceForm(forms.Form):
    init_date = forms.CharField(
        label = 'Fecha de inicio: ',
        widget = forms.DateInput(attrs={'class':'form-control datepicker','type':'date'})
    )
    end_date = forms.CharField(
        label = 'Fecha final: ',
        widget = forms.DateInput(attrs={'class':'form-control datepicker','type':'date'})
    )
    extra_time = forms.BooleanField(
        label = 'Solo tiempo extra',
        widget = forms.NullBooleanSelect(),
        initial = False,
        required = False,
    )
    adicionales = forms.BooleanField(
        label = 'Solo actividades adicionales',
        widget = forms.NullBooleanSelect(),
        initial = False,
        required=False,
    )

app/finances/views.py
from typing import Any
from django.db.models import Sum, Value, Avg
from django.http import HttpResponse

from django.views.generic import (
    CreateView, UpdateView, DeleteView, ListView, TemplateView,
    MonthArchiveView, FormView, RedirectView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from finances.models import Movement
from projects.models import Project, Report
from finances.forms import MovementCreateForm, DateSelectForm, AttendanceForm
from django.contrib.auth.models import User

import datetime

import pandas as pd

class MovementCreateView(LoginRequiredMixin,CreateView):
    model = Movement
    #fields = '__all__'
    form_class = MovementCreateForm
    success_url = reverse_lazy("finances:finances_home")

    def get_form_kwargs(self):
        kwargs = super(MovementCreateView, self).get_form_kwargs()
        u = self.request.user
        kwargs['initial']= {
            'responsable':u.pk,
        }
        return kwargs

    def get_context_data(self, *args, **kwargs):
        context =  super(MovementCreateView, self).get_context_data(*args, **kwargs)
        context['no_invoice'] = Movement.objects.filter(
            no_invoice = True,
            responsable = self.request.user.pk,
            creation_date__month = datetime.datetime.now().month,
        ).order_by('creation_date')
        context['invoice'] = Movement.objects.filter(
            no_invoice = False,
            responsable = self.request.user.pk,
            creation_date__month = datetime.datetime.now().month,
        ).order_by('creation_date')
        context['total_fact'] = context['invoice'].filter(
            no_invoice=False
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        context['total_no_fact'] = context['no_invoice'].filter(
            no_invoice = True
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        return context

class MovementUpdateView(LoginRequiredMixin, UpdateView):
    model = Movement
    #fields = '__all__'
    form_class = MovementCreateForm
    success_url = reverse_lazy("finances:finances_home")

    def get_context_data(self, *args, **kwargs):
        context =  super(MovementUpdateView, self).get_context_data(*args, **kwargs)
        context['no_invoice'] = Movement.objects.filter(
            no_invoice = True,
            responsable = self.request.user.pk,
            creation_date__month = datetime.datetime.now().month,
        ).order_by('creation_date')
        context['invoice'] = Movement.objects.filter(
            no_invoice = False,
            responsable = self.request.user.pk,
            creation_date__month = datetime.datetime.now().month,
        ).order_by('creation_date')
        context['total_fact'] = context['invoice'].filter(
            no_invoice=False
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        context['total_no_fact'] = context['no_invoice'].filter(
            no_invoice = True
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        return context

class MovementDeleteView(LoginRequiredMixin, DeleteView):
    model = Movement
    success_url = reverse_lazy("finances:finances_home")

class MovementAdminListView(LoginRequiredMixin, ListView):
    model = Movement
    context_object_name = 'movement_list'

class MovementMontArchiveView(LoginRequiredMixin, MonthArchiveView):
    model = Movement
    date_field = 'creation_date'
    year_format = '%Y'
    month_format = '%m'
    context_object_name ="movement_list"
    allow_empty = True
    allow_future = True

    def get_context_data(self, *args, **kwargs):
        context =  super(MovementMontArchiveView, self).get_context_data(*args, **kwargs)
        #print(self.request.GET.get('order_by'))
        if self.request.GET.get('order_by'):
            order_by = self.request.GET.get('order_by')
        else:
            order_by = 'creation_date'
        if self.request.GET.get('responsable'):
            responsable = self.request.GET.get('responsable')
        else:
            responsable = self.request.user.pk
        context['no_invoice'] = context['object_list'].filter(
            no_invoice = True,
            responsable = responsable
        ).order_by(order_by)
        context['invoice'] = context['object_list'].filter(
            no_invoice = False,
            responsable = responsable
        ).order_by(order_by)
        context['total_fact'] = context['invoice'].filter(
            no_invoice=False
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        context['total_no_fact'] = context['no_invoice'].filter(
            no_invoice = True
        ).aggregate(
            Sum('amount')
        )['amount__sum']
        return context

class UserAccountingTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'finances/useraccounting.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['resumen'] = User.objects.annotate(total = Sum('movement__amount')).filter(total__gt = 0)
        return context

class MovementLastMonth(LoginRequiredMixin, RedirectView):
    

    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        actual_date = datetime.date.today()
        url = 'movementlist/{}/{}?responsable={}'.format(
            actual_date.year,
            actual_date.month,
            self.request.GET.get('responsable')
        )
        return url
    # url=reverse_lazy("finances:finances_month", kwargs={
    #     'year':actual_date.year,
    #     'month':actual_date.month,
    # })
'''
Lista de tiempo dedicado por proyecto
'''
class WorkersTimeListView(LoginRequiredMixin, FormView):
    form_class = DateSelectForm
    template_name = 'finances/workers_time.html'
    success_url = reverse_lazy("finances:workerstime_list")
    extra_context = dict()

    def form_valid(self, form):
        projects = Project.objects.all()
        time_proyect_report = []
        inicio = form.cleaned_data["init_date"]
        final = form.cleaned_data["end_date"]
        #print('de {} hasta {}'.format(inicio, final))
        for project in projects:
            if project.activity_set.all():
                for act in project.activity_set.all():
                    for report in act.report_set.filter(date__range=[inicio, final]):
                        for u in report.workers.all():
                            time_proyect_report.append({
                                'project':'CC-INX-{}: {}'.format(project.cc_number, project.name),
                                'user':'{} {}'.format(u.first_name, u.last_name),
                                'time':report.duration
                            })
        df = pd.DataFrame(time_proyect_report)
        #print(df)
        df2 = df.groupby(['project','user'])['time'].sum()
        df3 = df.groupby(['project'])['time'].sum()
        self.extra_context['project_user'] = df2
        self.extra_context['project_time'] = df3
        self.extra_context['inicio'] = inicio
        self.extra_context['final'] = final
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        try:
            context['project_user'] = self.extra_context['project_user']
            context['project_time'] = self.extra_context['project_time']
            context['inicio'] = self.extra_context['inicio']
            context['final'] = self.extra_context['final']
            #print(context)
        except:
            projects = Project.objects.all()
            time_proyect_report = []
            for project in projects:
                if project.activity_set.all():
                    for act in project.activity_set.all():
                        for report in act.report_set.all():
                            for u in report.workers.all():
                                time_proyect_report.append({
                                    'project':'CC-INX-{}: {}'.format(project.cc_number, project.name),
                                    'user':'{} {}'.format(u.first_name, u.last_name),
                                    'time':report.duration
                                })
            df = pd.DataFrame(time_proyect_report)
            #print(df)
            df2 = df.groupby(['project','user'])['time'].sum()
            df3 = df.groupby(['project'])['time'].sum()
            context['project_user'] = df2
            context['project_time'] = df3
        result = []
        for key in context['project_time'].keys():
            df4 = context['project_user'].filter(like=key)
            trabajadores = []
            for index in df4[key].index:
                trabajadores.append({
                    'name':index,
                    'time':df4[key][index],
                })
            result.append({
                'nombre_de_proyecto':key,
                'horas_de_proyecto':context['project_time'][key],
                'horas_por_trabajador':trabajadores,
            })
        context['result'] = result
        return context
    
class AttendanceReport(LoginRequiredMixin, FormView):
    form_class = DateSelectForm
    template_name = "finances/attendance.html"
    success_url = reverse_lazy("finances:attendance_report")
    extra_context = dict()

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        delta = datetime.timedelta(days=1)
        users = User.objects.filter(is_active=True).order_by('last_name')
        calendar = []
        report_dates = []
        try:
            start_date = datetime.datetime.strptime(
                self.extra_context['inicio'],
                '%Y-%m-%d'
            )
            end_date = datetime.datetime.strptime(

app/finances/templates/finances/attendance.html
{% extends '__base.html' %}
{% load finance_extra %}

{% block title %}
    Lista de asistencia
{% endblock title %}

{% block content %}

<div class="col col-lg-3">
    <form method="post">
        {% csrf_token %}
        {{form.as_table}}
        <input class="btn btn-primary mb-3" type="submit" value="Actualizar">
    </form>
</div>

<h4>
Resultado
</h4>
{% if inicio %}
<h3>
desde {{ inicio }} hasta {{ final }}
</h3>


<table class="project-table">
    <thead>
        <tr>
            <th scope="col">
                Nombre
            </th>
            {% for each_day in days %}
            <th scope="col" class="colincl">
                {{ each_day|date:'Y-m-d' }}
            </th>
            {% endfor %}
        </tr>
    </thead>
    {% for user in calendar %}
    <tr>
        <th scope="row">{{user.user.last_name}} {{user.user.first_name}}</th>
        {% for day in user.hours %}
        <td scope="row">
        {% if day > 0 %}
            {{day|floatformat}}
        {% else %}
             - - 
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% else %}
<h3>
Ingrece un rango de fechas
</h3>
{% endif %}
{% endblock content %}

app/finances/templates/finances/attendance_form.html
{% extends '__base.html' %}
{% load finance_extra %}

{% block title %}
    Lista de asistencia
{% endblock title %}

{% block content %}

<div class="col col-lg-3">
    <form method="post">
        {% csrf_token %}
        {{form.as_table}}
        <input class="btn btn-primary mb-3" type="submit" value="Crear reporte">
    </form>
</div>

<h4>
Resultado
</h4>
{% if inicio %}
<h3>
desde {{ inicio }} hasta {{ final }}
</h3>


<table class="project-table">
    <thead>
        <tr>
            <th scope="col">
                Nombre
            </th>
            {% for each_day in days %}
            <th scope="col" class="colincl">
                {{ each_day|date:'Y-m-d' }}
            </th>
            {% endfor %}
        </tr>
    </thead>
    {% for user in calendar %}
    <tr>
        <th scope="row">{{user.user.last_name}} {{user.user.first_name}}</th>
        {% for day in user.hours %}
        <td scope="row">
        {% if day > 0 %}
            {{day|floatformat}}
        {% else %}
             - - 
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% else %}
<h3>
Ingrece un rango de fechas
</h3>
{% endif %}
{% endblock content %}

app/finances/templates/finances/attendance_report.html
{% extends '__base.html' %}
{% load finance_extra %}

{% block title %}
    Lista de asistencia
{% endblock title %}

{% block content %}

<h3>
desde {{ inicio }} hasta {{ final }}
</h3>


<table class="project-table">
    <thead>
        <tr>
            <th scope="col">
                Nombre
            </th>
            {% for each_day in days %}
            <th scope="col" class="colincl">
                {{ each_day|date:'Y-m-d' }}
            </th>
            {% endfor %}
        </tr>
    </thead>
    {% for user in calendar %}
    <tr>
        <th scope="row">{{user.user.last_name}} {{user.user.first_name}}</th>
        {% for day in user.hours %}
        <td scope="row">
        {% if day > 0 %}
            {{day|floatformat}}
        {% else %}
             - - 
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% endblock content %}

app/finances/templates/finances/movement_archive_month.html
{% extends '__base.html' %}
{% load finance_extra %}

{% block title %}
    Movimientos mensuales
{% endblock title %}

{% block content %}
<div class="col col-lg-9">
    <h3>Balance del mes {{ month|date:'b' }}</h3>
    <p>
        Total facturable: ${{total_fact|stringformat:"2.2f"}}
    </p>
    <p>
        Total no facturable: ${{total_no_fact|stringformat:"2.2f"}}
    </p>

    <h3>Movimientos facturables</h3>
    <table class="project-table">
        <thead>
            <tr>
                <th scope="col">
                    {% if '?order_by=payee' in request.get_full_path %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}?order_by=-payee">
                    {% else %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}?order_by=payee">
                    {% endif %}
                        Proveedor
                    </a>
                </th>
                <th scope="col">
                    {% if '?order_by=-creation_date' in request.get_full_path %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}">
                    {% else %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}?order_by=-creation_date">
                    {% endif %}
                        Día
                    </a>
                </th>
                <th scope="col">Descripción</th>
                <th scope="col">
                    {% if '?order_by=amount' in request.get_full_path %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}?order_by=-amount">
                    {% else %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}?order_by=amount">
                    {% endif %}
                        Monto
                    </a>
                </th>
                <th scope="col">Pago</th>
                <th scope="col">Archivo</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        {% for reg in invoice %}
        <tr {% if reg.amount < 0 %}
        class="negative"
        {% endif %}>
            <td scope="col">{{ reg.payee }}</td>
            <td scope="col">{{ reg.creation_date|date:"d" }}</td>
            {% if reg.description|wordcount > 10 %}
            <td scope="col" title="{{ reg.description }}">
                    {{ reg.description|truncatewords:'10' }}
            </td>
            {% else %}
            <td scope="col">{{ reg.description }}</td>
            {% endif %}
            <td scope="col">{{ reg.amount|stringformat:"2.2f" }}</td>
            <td scope="col">
                {% if reg.payment %}
                    &#9745; 
                {% else %}
                    &#9744;
                {% endif %}
            <td scope="col">
                {% if reg.files %}
                <a href="{{ reg.files.url }}">{{reg.files|filename}}</a>
                {% endif %}
            </td>
            <th scope="col"><a class="btn btn-outline-danger" href="{% url 'finances:finances_delete' reg.pk %}" role="button">&#9249;</a></th>
        </tr>
        {% endfor %}
    </table>
    <h3>Movimientos NO facturables</h3>

    <table class="project-table">
        <thead>
            <tr>
                <th scope="col">
                    {% if '?order_by=payee' in request.get_full_path %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}?order_by=-payee">
                    {% else %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}?order_by=payee">
                    {% endif %}
                        Proveedor
                    </a>
                </th>
                <th scope="col">
                    {% if '?order_by=-creation_date' in request.get_full_path %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}">
                    {% else %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}?order_by=-creation_date">
                    {% endif %}
                        Día
                    </a>
                </th>
                <th scope="col">Descripción</th>
                <th scope="col">
                    {% if '?order_by=amount' in request.get_full_path %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}?order_by=-amount">
                    {% else %}
                    <a href="{% url 'finances:finances_month' month|date:'Y' month|date:'m' %}?order_by=amount">
                    {% endif %}
                        Monto
                    </a>
                </th>
                <th scope="col">Pago</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        {% for reg in no_invoice %}
        <tr {% if reg.amount < 0 %}
        class="negative"
        {% endif %}>
            <td scope="col">{{ reg.payee }}</td>
            <td scope="col">{{ reg.creation_date|date:"d" }}</td>
            {% if reg.description|wordcount > 10 %}
            <td scope="col" title="{{ reg.description }}">
                    {{ reg.description|truncatewords:'10' }}
            </td>
            {% else %}
            <td scope="col">{{ reg.description }}</td>
            {% endif %}
            <td scope="col">${{ reg.amount|stringformat:"6.2f" }}</td>
            <td scope="col">
                {% if reg.payment %}
                    &#9745;    
                {% else %}
                    &#9744;
                {% endif %}
            <th scope="col"><a class="btn btn-outline-danger" href="{% url 'finances:finances_delete' reg.pk %}" role="button">&#9249;</a></th>
        </tr>
        {% endfor %}
    </table>
</div>

{% url 'finances:finances_month' previous_month|date:'Y' previous_month|date:'m' as prev_url %}
{% url 'finances:finances_month' next_month|date:'Y' next_month|date:'m' as next_url %}

<table class="project-table">
    <tr>
        <td colspan="2">
        {% if previous_month %}
        <a class="button" 
        href="{{prev_url}}{% if request.GET.responsable %}?responsable={{ request.GET.responsable }}{%endif%}">
            Año: {{ previous_month|date:'Y' }} Mes: {{ previous_month|date:'m' }}</a>
        {% endif %}
        </td>
        <td colspan="2">
        {% if next_month %}
        <a class="button" href="{{next_url}}{% if request.GET.responsable %}?responsable={{ request.GET.responsable }}{%endif%}">
        Año: {{ next_month|date:'Y' }} Mes: {{ next_month|date:'m' }}
        </a>
        {% endif %}
        </td>
    </tr>
</table>




{% endblock %}

app/finances/templates/finances/movement_form.html
{% extends '__base.html' %}
{% load finance_extra %}

{% block title %}
    Movimientos
{% endblock title %}

{% block content %}

<div class="col col-lg-3">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_table}}
        <input class="btn btn-primary mb-3" type="submit" value="Enviar">
    </form>
</div>

<div class="col col-lg-9">
    <h3>Balance del mes actual</h3>
    <p>
        Total facturable: ${{total_fact|floatformat:"2g"}}
    </p>
    <p>
        Total no facturable: ${{total_no_fact|floatformat:"2g"}}
    </p>

    <h3>Movimientos facturables</h3>
    <table class="project-table">
        <thead>
            <tr>
                <th scope="col">Proveedor</th>
                <th scope="col">Día</th>
                <th scope="col">Descripción</th>
                <th scope="col">Monto</th>
                <th scope="col">Pagado</th>
                <th scope="col">Archivo</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        {% for reg in invoice %}
        <tr {% if reg.amount < 0 %}
        class="negative"
        {% endif %}>
            <td scope="col">{{ reg.payee }}</td>
            <td scope="col">{{ reg.creation_date|date:"d" }}</td>
            {% if reg.description|wordcount > 10 %}
            <td scope="col" title="{{ reg.description }}">
                    {{ reg.description|truncatewords:'10' }}
            </td>
            {% else %}
            <td scope="col">{{ reg.description }}</td>
            {% endif %}
            <td scope="col">{{ reg.amount|floatformat:"2g" }}</td>
            <td scope="col">
                {% if reg.payment %}
                    &#9745; 
                {% else %}
                    &#9744;
                {% endif %}
            <td scope="col">
                {% if reg.files %}
                <a href="{{ reg.files.url }}">{{reg.files|filename}}</a>
                {% endif %}
            </td>
            <th scope="col"><a class="btn btn-outline-danger" href="{% url 'finances:finances_delete' reg.pk %}" role="button">&#9249;</a></th>
        </tr>
        {% endfor %}
    </table>

    <h3>Movimientos NO facturables</h3>

    <table class="project-table">
        <thead>
            <tr>
                <th scope="col">Proveedor</th>
                <th scope="col">Día</th>
                <th scope="col">Description</th>
                <th scope="col">Monto</th>
                <th scope="col">Pago</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        {% for reg in no_invoice %}
        <tr {% if reg.amount < 0 %}
        class="negative"
        {% endif %}>
            <td scope="col">{{ reg.payee }}</td>
            <td scope="col">{{ reg.creation_date|date:"d" }}</td>
            {% if reg.description|wordcount > 10 %}
            <td scope="col" title="{{ reg.description }}">
                    {{ reg.description|truncatewords:'10' }}
            </td>
            {% else %}
            <td scope="col">{{ reg.description }}</td>
            {% endif %}
            <td scope="col">${{ reg.amount|floatformat:"2g" }}</td>
            <td scope="col">
                {% if reg.payment %}
                    &#9745;    
                {% else %}
                    &#9744;
                {% endif %}
            <th scope="col"><a class="btn btn-outline-danger" href="{% url 'finances:finances_delete' reg.pk %}" role="button">&#9249;</a></th>
        </tr>
        {% endfor %}
    </table>
</div>

<a class="button" href="{% url 'finances:finances_lastmonth' %}">
    Historico
</a>

{% endblock content %}

{% block scripts %}
{% endblock %}

app/finances/templates/finances/useraccounting.html
{% extends '__base.html' %}
{% load finance_extra %}

{% block title %}
Resumen de viaticos
{% endblock title %}

{% block content %}
{% load static %}
<div class="col col-lg-9">
    <h3>
        Resumen de viaticos
    </h3>
    <p>
        {% for each in resumen %}
        <p> 
            <a href="{% url 'finances:finances_lastmonth' %}?responsable={{each.pk}}">
                <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
            {{each.last_name}}, {{each.first_name}}: $ {{each.total|stringformat:"2.2f"}}
        </p>
        {% endfor %}
    </p>
{% endblock %}