app/finances/urls.py
from django.urls import path
from finances.views import (MovementCreateView, MovementUpdateView, MovementDeleteView,
                            MovementMontArchiveView,MovementLastMonth ,MovementAdminListView,
                            WorkersTimeListView, AttendanceReport, AttendanceReportFormClass,
                            AttendaceFullReportClass, UserAccountingTemplateView,
                            ProjectAttendanceReport)

app_name = 'finances'

urlpatterns = [
    path('', MovementCreateView.as_view(), name = 'finances_home'),
    path('currentmonth',MovementLastMonth.as_view(), name='finances_lastmonth'),
    path('movementlist/<int:year>/<int:month>', MovementMontArchiveView.as_view(), name='finances_month'),
    path('movementresume', UserAccountingTemplateView.as_view(), name='finances_resume'),
    path('edit/<int:pk>', MovementUpdateView.as_view(), name = 'finances_edit'),
    path('delete/<int:pk>', MovementDeleteView.as_view(), name='finances_delete'),
    path('workerstime', WorkersTimeListView.as_view(), name='workerstime_list'),
    #path('attendance', AttendanceReport.as_view(), name='attendance_report'),
    path(
        'attendance/<str:inicio>/<str:final>/<str:extra>/<str:adicional>',
        AttendaceFullReportClass.as_view(),
        name='attendance_report'),
    path('attendanceform', AttendanceReportFormClass.as_view(), name='attendance_form'),
    path(
        'projectattendance/<int:pk>',
        ProjectAttendanceReport.as_view(),
        name='projectattendance_report'
    ),
]

app/inxcontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('inxcontrol/admin/', admin.site.urls),
    path('inxcontrol/profiles/', include('profiles.urls'), name='profiles'),
    path('inxcontrol/finances/', include('finances.urls'), name='finances'),
    path('inxcontrol/projects/', include('projects.urls'), name='projects'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

app/projects/urls.py
from django.urls import path

from .views import ( ProjectCreateView, ProjectListView, ProjectDetailView,
                     ProjectUpdateView, ActivityCreateView, ActivityDetailView,
                     ActivityListView, RequirementCreateView, RequirementListView,
                     ReportCreateView, ReportListView, ReportUpdateView, ActivityUpdateView,
                     ReportDetailView, PhotoCreateView, RequirementUpdateView,
                     ActivityDeleteView, ActivityCompactListView, ReportCardListView,
                     ActivityProgressCreateView, ReportProgressCreateView,
                     ActivityProgressUpdateView, ReportProgressUpdateView,
                     ReportProgressDeleteView, ActivityProgressDeleteView, SearchListView,
                     ReportDeleteView, ReportDayArchiveView, ReportLastdayArchiveView,
                     ActivityPrintView, RequirementCompleteView )
app_name = 'projects'

urlpatterns = [
    path('projectlist', ProjectListView.as_view(), name='project_list' ),
    path('projectcreate', ProjectCreateView.as_view(),name='project_create'),
    path("projectdetail/<int:pk>", ProjectDetailView.as_view(), name = 'project_detail'),
    path('projectupdate/<int:pk>', ProjectUpdateView.as_view(), name='project_update' ),
    path('activitylist', ActivityListView.as_view(), name='activity_list'),
    path('activityprint', ActivityPrintView.as_view(), name='activity_print'),
    path('activitycompactlist', ActivityCompactListView.as_view(), name='activity_compactlist'),
    path('activitycreate', ActivityCreateView.as_view(), name='activity_create'),
    path('activitydetail/<int:pk>', ActivityDetailView.as_view(), name='activity_detail'),
    path('activityupdate/<int:pk>', ActivityUpdateView.as_view(), name='activity_update'),
    path('activitydelete/<int:pk>', ActivityDeleteView.as_view(), name='activity_delete'),
    path('activityprogresscreate/<int:pk>', ActivityProgressCreateView.as_view(), name='activityprogress_create'),
    path('activityprogressupdate/<int:pk>', ActivityProgressUpdateView.as_view(), name='activityprogress_update'),
    path('activityprogressdelete/<int:pk>', ActivityProgressDeleteView.as_view(), name='activityprogress_delete'),
    path('requirementcreate', RequirementCreateView.as_view(), name='requirement_create'),
    path('requirementupdate/<int:pk>', RequirementUpdateView.as_view(), name='requirement_update'),
    path('requirementlist', RequirementListView.as_view(), name='requirement_list'),
    path('requirementcomplete/<int:pk>', RequirementCompleteView.as_view(), name='requirement_complete'),
    path('reportlist', ReportListView.as_view(), name='report_list'),
    path('reports/lastday', ReportLastdayArchiveView.as_view(), name='report_lastday'),
    path('reports/<int:year>/<str:month>/<int:day>/', ReportDayArchiveView.as_view(), name='report_dayarchive'),
    path('reportcardlist', ReportCardListView.as_view(), name='report_cardlist'),
    path('reportcreate', ReportCreateView.as_view(), name='report_create'),
    path('reportcreate/<int:pk>', ReportProgressCreateView.as_view(), name='report2_create'),
    path('reportdelete/<int:pk>', ReportDeleteView.as_view(), name='report_delete'),
    path('reportprogressupdate/<int:pk>', ReportProgressUpdateView.as_view(), name='reportprogress_update'),
    path('reportprogresdelete/<int:pk>', ReportProgressDeleteView.as_view(), name='reportprogress_delete'),
    path('reportupdate/<int:pk>', ReportUpdateView.as_view(), name='report_update'),
    path('reportdetail/<int:pk>', PhotoCreateView.as_view(), name='report_detail'),
    path('search', SearchListView.as_view(), name='all_search'),
]

app/finances/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Supplier
from datetime import datetime

import os

class Movement(models.Model):
    payee = models.ForeignKey(
        Supplier,
        models.SET_NULL,
        blank = True,
        null = True
    )
    creation_date = models.DateField(
        default = datetime.now,
    )
    description = models.CharField(
        max_length=254
    )
    amount = models.DecimalField(
        decimal_places=3,
        max_digits=7
    )
    no_invoice = models.BooleanField(
        blank = True,
        default = False
    )
    payment = models.BooleanField(
        blank = True,
        default = False
    )
    responsable = models.ForeignKey(
        User,
        models.CASCADE
    )
    files = models.FileField(
        upload_to="finances/%Y/%m/%d/",
        blank = True,
        null = True
    )

app/projects/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save

from profiles.models import Client, ClientContact
from django.contrib.auth.models import User
from django.core.files.uploadedfile import UploadedFile

from datetime import datetime
import os
from PIL import Image

def get_image_path(instance, filename):
    # print(instance.report.id)
    return os.path.join('reportes', str(instance.report.id), filename)

def get_thumbails_path(instance, filename):
    # print(instance.report.id)
    return os.path.join('thumbnails', filename)

class Project(models.Model):
    class Status(models.IntegerChoices):
        ACTIVO = 0, ("Activo")
        CIERRE_DOC = 1, ("Cierre Documental")
        PAUSADO = 2, ("Pausado")
        CERRADO = 3, ("Cerrado")
        CANCELADO = 4, ("Cancelado")
    
    class Types(models.IntegerChoices):
        PROY = 0, ("Proyecto")
        SUMI = 1, ("Suministro")
        SERV = 2, ("Servicio")
        FABR = 3, ("Fabricación")
        NOCO = 4, ("No contratado")

    cc_number = models.IntegerField(
        unique=True,
        null=True,
        blank=True,
        help_text="Numero de centro de costo"
    )
    name = models.CharField(
        max_length=255,
        help_text="Nombre del proyecto",
        null=True,
        blank=True,
    )
    type = models.IntegerField(
        choices=Types.choices,
        default=0,
        help_text="Tipo de proyecto",
        null=True,
    )
    date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default = datetime.now,
        null=True,
        blank=True,
        help_text='Fecha de inicio'
    )
    end_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        null = True,
        blank = True,
        help_text = "Fecha final del proyecto"
    )
    client = models.ForeignKey(
        Client,
        on_delete=models.SET_NULL,
        related_name='%(class)s_client',
        null = True,
        blank = True,
        help_text = "Nombre del cliente"
    )
    contact = models.ManyToManyField(
        ClientContact,
        blank = True,
    )
    manager = models.ForeignKey(
        User,
        null = True,
        blank = True,
        on_delete=models.SET_NULL,
        help_text = "Es quien dara seguimiento al proyecto"
    )
    status = models.IntegerField(
        choices=Status.choices,
        default=0,
        help_text="Estado actual del proyecto",
        null=True
    )

    def __str__(self):
        return 'INX-CC-{}: {}'.format(self.cc_number, self.name)

class Activity(models.Model):
    class Status(models.IntegerChoices):
        NEW = 0, ('Nueva')
        IN_PROCESS = 1, ('En proceso')
        FINISHED = 2, ('Terminada')
        UNFINISHED = 3, ('Incompleta')
        CANCELED  = 4, ('Cancelada')
        
    class Types(models.IntegerChoices):
        ADDITIONAL = 0, ('Adicional')
        PROJECT = 1, ('Proyecto')
        ENGINEERING = 2, ('Ingenieria')
        SERVICE = 3, ('Servicio')
        OTHER  = 4, ('Otro')

    name = models.CharField(
        max_length= 50,
        help_text="Nombre corto de la actividad"
    )
    date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default = datetime.now,
        null=True,
        blank=True,
        help_text='Fecha de inicio'
    )
    end_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        null = True,
        blank = True,
        help_text = "Fecha estimada final de la actividada"
    )
    description = models.TextField(
        max_length=500,
        help_text="Descripcion adicional de la actividad si es necesario",
        null=True,
        blank=True,
    )
    type = models.IntegerField(
        choices=Types.choices,
        default = 0,
        help_text="Tipo de actividad",
    )
    status = models.IntegerField(
        choices=Status.choices,
        default = 0,
        help_text="Estado de la actividad"
    )
    project = models.ForeignKey(
        Project,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
        help_text = "Projecto al que pertenece")
    incharge = models.ForeignKey(
        User,
        null = True,
        blank = True,
        on_delete=models.SET_NULL,
        help_text = "Es el responsable de la actividad")

    def __str__(self):
        if self.project:
            return str(self.project.name) + ': ' + str(self.name)
        else:
            return 'Sin proyecto: ' + self.name
        
    @receiver(post_save, sender=Project)
    def create_default_activity(sender, instance, created, **kwargs):
        if created:
            if instance.status == 0:
                act = Activity()
                act.name = "No planeadas CC-INX-" + str(instance.cc_number)
                act.description = instance
                act.project = instance
                act.save()

class ActivityProgress(models.Model):
    name = models.CharField(
        max_length=96,
        null=True,
        blank = True,
        help_text='Nombre de la medida de progreso'
    )
    amount = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        blank=True,
        null=True,
        help_text='Cantidad requerida',
    )
    unit = models.CharField(
        max_length=32,
        null=True,
        blank=True,
        help_text='Unidad de medida',
    )
    activity = models.ForeignKey(
        Activity,
        on_delete=models.CASCADE,
        null=True,
        help_text='En que actividad se utiliza',
    )

class Requirements(models.Model):
    class status(models.IntegerChoices):
        PENDIENTE = 0, ('Pendiente')
        COMPLETO = 1, ('Completado')
        CANCEL = 2, ('Cancelado')

    name = models.CharField(
        max_length=50,
        help_text="Nombre corto del requerimiento"
    )
    request_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default = datetime.now,
        null=True,
        blank=True,
        help_text='Fecha de solicitud'
    )
    supply_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default = datetime.now,
        null=True,
        blank=True,
        help_text='Fecha de inicio'
    )
    by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_by',
        blank=True,
        null=True,
        help_text="Trabajador que solicita el requerimiento"
    )
    to = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_to',
        blank=True,
        null=True,
        help_text="Trabajador que debe entregar el requerimiento"
    )
    description=models.TextField(
        max_length=255,
        help_text="Descripcion de requerimiento",
    )
    amount=models.IntegerField(
        default=1,
        help_text="Cantidad de unidades del requerimiento"
    )
    unit = models.CharField(
        max_length=10,
        help_text="Unidad en las que se contabiliza el requerimiento"
    )
    activity = models.ForeignKey(
        Activity,
        on_delete=models.PROTECT,
        related_name='%(class)s_activities',
    )
    status = models.IntegerField(
        choices=status.choices,
        default = 0,
        help_text="Estado del requerimiento"
    )

    def __str__(self):
        return self.name

class Report(models.Model):
    class Deadtimetype(models.IntegerChoices):
        CLIENT = 0, ('A causa del cliente')
        MATERIAL = 1, ('Espera de materiales')
        WORKERS = 2, ('Espera de trabajadores')
        COMPLEX = 3, ('Tarea demaciado compleja')

    responsable = models.ForeignKey(
        User,
        related_name='%(class)s_responsable',
        on_delete=models.SET_NULL,
        null = True,
        blank = True,
        help_text = "Responsable de la actividad")
    date = models.DateField(
        default = datetime.now,
        help_text = "Fecha de la actividad AAAA-MM-DD"
    )
    name = models.CharField(
        max_length = 80,
        null=True,
        blank=True,
        help_text = "Nombre corto del reporte"
    )
    activity = models.ForeignKey(
        Activity,
        on_delete=models.SET_NULL,
        help_text="Seleccione la actividad",
        null=True,
        blank=True,
    )
    description = models.TextField(
        max_length=4096,
        help_text = "Descripción",
        null = True,
        blank = True)
    workers = models.ManyToManyField(
        User,
        related_name='%(class)s_workers',
        blank = True,
        help_text = "Ayudantes",
        null = True)
    duration = models.DecimalField(
        max_digits = 4,
        decimal_places = 2,
        null = True,
        blank = True,
        help_text = "Duración hora con punto decimal 1.5 = 1:30")
    deadtime = models.IntegerField(
        default=0,
        help_text="Tiempo muerto en minutos")
    deadtimereason = models.IntegerField(
        choices=Deadtimetype.choices,
        default=0,
        help_text="Razón por la cual se dio el tiempo muerto"
    )
    extratime = models.BooleanField(
        blank=True,
        null=True,
        help_text="Marcar si el reporte es en horas extras",
    )

    def __str__(self):
        if self.name:
            return self.name
        else:
            return  self.date.strftime("%d/%m/%Y")

class ReportProgress(models.Model):
    amount = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=0.0,
        blank=True,
        null=True,
        help_text='Cantidad avanzada',
    )
    activityprogress = models.ForeignKey(
        ActivityProgress,
        on_delete=models.CASCADE,
        null=True,
        help_text='A cual requerimiento hace referencia',
    )
    report = models.ForeignKey(
        Report,
        on_delete=models.CASCADE,
        null = True,
        help_text='Reporte en el cual se hizo el avance',

app/projects/templates/projects/activity_confirm_delete.html
{% extends '__base.html' %}

{% block title %}
    Borrar actividad
{% endblock title %}

{% block content %}

<p>Seguro de borrar la actividad: ID:{{activity.pk}} nombre:{{activity.name}}</p>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Borar">
</form>

{% endblock content %}

app/projects/templates/projects/activity_detail.html
{% extends '__base.html' %}

{% block title %}
    Detalle de actividad
{% endblock title %}

{% block content %}
{% load static %}
<h3>Actividad {{activity.id|stringformat:"03d"}}: {{activity.name}}</h3>

<div class="responsive-two-column-grid">
    <div>
        <ul>
            <li><b>Desde: </b>{{activity.date|date:'d-m-Y'}}</li>
            <li><b>Hasta: </b>{{activity.end_date|date:'d-m-Y'}}</li>
            <li>
                <b>Proyecto: </b>
                {% if activity.project %}
                    {{activity.project|truncatewords:'4'}}
                    <a href="{% url 'projects:project_detail' activity.project.pk %}">
                        <img src = "{% static 'icons/icons-link.png' %}" alt="edit-icon" width="15" />
                    </a>
                {% endif %}
            </li>
            <li>
                <b>Responsable: </b>
                {% if activity.incharge %}
                {{activity.incharge.first_name}} {{activity.incharge.last_name}}
                <a href="{% url 'profiles:user_detail' activity.incharge.pk %}">
                    <img src = "{% static 'icons/icons-link.png' %}" alt="edit-icon" width="15" />
                </a>
                {% endif %}
            </li>
            <li><b>Fin: </b>{{activity.end_date|date:'d-m-Y'}}</li>
            <li><b>Tipo: </b>{{activity.get_type_display|title}}</li>
            <li><b>Estado: </b>{{activity.get_status_display|title}}</li>
            <li><b>Acciones</b>
                            <a class='button' href="{% url 'projects:activity_detail' activity.id %}">detalle</a>
                            <a class='button' href="{% url 'projects:activity_update' activity.id %}">Editar</a>
                            <a class='button' href="{% url 'projects:activity_delete' activity.id %}">Borrar</a></li>
            <li><b>MEDICIONES:</b></li>
            <ul>
                {% for activityprogress in progress %}
                    <li>
                        {{ activityprogress.name }}: 
                        {% if activityprogress.total %}
                            {{ activityprogress.total|floatformat }} 
                        {% else %}
                            0 
                        {% endif %}
                        de {{activityprogress.goal|floatformat}} {{ activityprogress.unit}}
                        <a href="{% url 'projects:activityprogress_update' activityprogress.id %}">
                            <img src = "{% static 'icons/icons-edit.svg' %}" alt="edit-icon"/>
                        </a>
                        <a href="{% url 'projects:activityprogress_delete' activityprogress.id %}">
                            <img src = "{% static 'icons/icons-delete.svg' %}" alt="delete-icon"/>
                        </a>
                        
                        <div id="progress">
                            <span id="percent">{{activityprogress.percent}}%</span>
                            <div id="bar" style="width: {{ activityprogress.percent }}%;"></div>
                        </div>
                    </li>
                {% endfor %}
                <li> <a class='button' href="{% url 'projects:activityprogress_create' activity.id %}">Agregar</a> </li>
            </ul>
            <li><b>REPORTES: </b></li>
            <ul>
                {% for report in activity.report_set.all%}
                    <li>
                        <a href="{% url 'projects:report_detail' report.pk %}">{{ report.date }}.- 
                            {% if report.name %}
                                {{ report.name }}
                            {% else %}
                                {% for progress in report.reportprogress_set.all %}
                                    {{ progress.amount|floatformat }} de {{ progress.activityprogress.amount|floatformat }} {{ progress.activityprogress.unit }}, 
                                {% endfor %}
                            {% endif %}
                        </a>, 
                    </li>
                {% endfor %}
                <li><a class="button" href="{% url 'projects:report_create' %}?activity={{activity.pk}}">Nuevo reporte</a></li>
            </ul>
        </ul>
    </div>
    <div>
        <b>Nombre: </b>{{activity.name}}</br>
        <b>Descripción: </b>{{ activity.description|linebreaks}}</br>
        <div class='thumbnail'>
        {% for report in activity.report_set.all%}
            {% for photo in report.photo_set.all %}
                    <a href="{{photo.pictures.url}}">
                        {% if photo.thumbnail %}
                            <img src="{{photo.thumbnail.url}}">
                        {% else %}
                            <img src = "{% static 'icons/icon-file.svg' %}" alt="file-icon"/>
                        {% endif %}
                    </a>
            {% endfor %}
        {% endfor %}
        </div>
    </div>
</div>
</br>

{% endblock content %}

app/projects/templates/projects/activity_form.html
{% extends '__base.html' %}

{% block title %}
    Formulario de actividad
{% endblock title %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Agregar">
</form>

{% endblock content %}

app/projects/templates/projects/activity_list.html
{% extends '__base.html' %}

{% block title %}
    Lista de Actividades
{% endblock title %}

{% block content %}
{% load static %}
<a class='button' href="{% url 'projects:activity_create' %}">Nueva actividad</a>
<a class='button' href="?status=1">Activas</a>
<a class='button' href="{% url 'projects:activity_compactlist' %}">Lista compacta</a>
<a class='button' href="?type=1">Solo planeadas</a>
<a class='button' href="?type=0">Solo adicionales</a>
<a class='button' href="?status=0">Todos</a>
{% for activity in activity_list %}
<div class="responsive-two-column-grid">
    <div>
        <ul>
            <li>
                <b>ID / Inicio: </b>
                {{activity.pk|stringformat:"03d"}} / {{activity.date|date:'d-m-Y'}}
                <a href="{% url 'projects:activity_detail' activity.id %}">
                    <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
                <a href="{% url 'projects:activity_update' activity.id %}">
                    <img src = "{% static 'icons/icons-edit.svg' %}" alt="edit-icon"/></a>
                </a>
                <a href="{% url 'projects:activity_delete' activity.id %}">
                    <img src = "{% static 'icons/remove.png' %}" alt="remove-icon" width="15" /></a>
            </li>
            <li>
                <b>Proyecto: </b>
                {% if activity.project %}
                    {{activity.project|truncatewords:'4'}}
                    <a href="{% url 'projects:project_detail' activity.project.pk %}">
                        <img src = "{% static 'icons/icons-link.png' %}" alt="edit-icon" width="15" />
                    </a>
                {% endif %}
            </li>
            <li>
                <b>Responsable: </b>
                {% if activity.incharge %}
                {{activity.incharge.first_name}} {{activity.incharge.last_name}}
                <a href="{% url 'profiles:user_detail' activity.incharge.pk %}">
                    <img src = "{% static 'icons/icons-link.png' %}" alt="edit-icon" width="15" />
                </a>
                {% endif %}
            </li>
            <li><b>Fin: </b>{{activity.end_date|date:'d-m-Y'}}</li>
            <li><b>Tipo: </b>{{activity.get_type_display}}</li>
            <li><b>Estado: </b>{{activity.get_status_display}}</li>
        </ul>
    </div>
    <div>
        <b>Nombre: </b>{{activity.name}}</br>
        <b>Descripción: </b>{{ activity.description}}</br>
        <div class='thumbnail'>
        {% for report in activity.report_set.all%}
            {% for photo in report.photo_set.all %}
                    <a href="{{photo.pictures.url}}">
                        {% if photo.thumbnail %}
                            <img src="{{photo.thumbnail.url}}">
                        {% else %}
                            <img src = "{% static 'icons/icon-file.svg' %}" alt="file-icon"/>
                        {% endif %}
                    </a>
            {% endfor %}
        {% endfor %}
        </div>
    </div>
</div>
{% endfor %}

    
</table>

<div class="pagination">
    {% if page_obj.has_previous %}
    {% if request.GET.status %}
    <a class='button' href="?status={{request.GET.status}}&page=1">&laquo; primera</a>
    <a class='button' href="?status={{request.GET.status}}&page={{ page_obj.previous_page_number }}">anterior</a>
    {% else %}
    <a class='button' href="?page=1">&laquo; primera</a>
    <a class='button' href="?page={{ page_obj.previous_page_number }}">anterior</a>
    {% endif %}
    {% endif %}
    
    <span>pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>
    
    {% if page_obj.has_next %}
    {% if request.GET.status %}
    <a class='button' href="?status={{request.GET.status}}&page={{ page_obj.next_page_number }}">sigueinte</a>
    <a class='button' href="?status={{request.GET.status}}&page={{ page_obj.paginator.num_pages }}">ultima &raquo;</a>
    {% else %}
        <a class='button' href="?page={{ page_obj.next_page_number }}">sigueinte</a>
        <a class='button' href="?page={{ page_obj.paginator.num_pages }}">ultima &raquo;</a>
    {% endif %}
    {% endif %}
</div>
{% endblock content %}

app/projects/templates/projects/activityprogress_confirm_delete.html
{% extends '__base.html' %}

{% block title %}
    Borrar avance de actividad
{% endblock title %}

{% block content %}

<p>Seguro de borrar el avance {{activityprogress.name}} de la actividad {{activityprogress.activity.name}}</p>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Borar">
</form>

{% endblock content %}

app/projects/templates/projects/project_detail.html
{% extends '__base.html' %}

{% block title %}
    Detalle de proyecto
{% endblock title %}

{% block content %}
{% load static %}
<h3>CC-INX-{{project.cc_number|stringformat:"03d"}}.- {{project.name}}</h3>
<a class='button' href="{% url 'projects:project_update' project.pk %}">EDITAR</a>
<a class='button' href="{% url 'projects:report_update' project.pk %}">BORRAR</a>
<a class='button' href="{% url 'projects:activity_create'%}?project={{project.pk}}">CREAR ACTIVIDAD</a>
{% if perms.finances.change_movement %}
<a class='button' href="{% url 'finances:projectattendance_report' project.pk%}">REPORTE</a>
{% endif %}

<div class="responsive-two-column-grid">
    <div>
        <ul>
            <li><b>Fecha de inicio: </b>{{project.date|date:'d-m-Y'}}</li>
            <li><b>Fecha final: </b>{{project.end_date|date:'d-m-Y'}}</li>
            <li><b>Cliente: </b>{{project.client|title}}</li>
            <li><b>Responsable: </b>{{project.manager.last_name|title}}, {{project.manager.first_name|title}}</li>
            <li><b>Estado: </b>{{project.get_status_display|title}}</li>
            <li><b>REGISTROS:</b>
            <ul>
            {% for activity in project.activity_set.all %}
                <li>
                    <a href="{% url 'projects:activity_detail' activity.pk %}">
                    Actividad: {{ activity.name }}
                    </a>
                </li>
                <ul>
                    {% for report in activity.report_set.all%}
                        <li>
                            <a href="{% url 'projects:report_detail' report.pk %}">{{ report.date }}.- {{ report.name }}</a>, 
                        </li>
                    {% endfor %}
                </ul>
            {% endfor %}
            </ul>
            </li>
        </ul>
    </div>
    <div>
        <b>Fotos: </b>
        <div class='thumbnail'>
        {% for activity in project.activity_set.all %}
            {% for report in activity.report_set.all%}
                {% for photo in report.photo_set.all %}
                    <div>
                        <a href="{{photo.pictures.url}}">
                            {% if photo.thumbnail %}
                            <img src="{{photo.thumbnail.url}}">
                        {% else %}
                            <img src = "{% static 'icons/icon-file.svg' %}" alt="file-icon"/>
                        {% endif %}
                        </a>
                    </div>
                {% endfor %}
            {% endfor %}
        {% endfor %}
        </div>
    </div>
</div>
</br>

{% endblock content %}

app/projects/templates/projects/report2_form.html
{% extends '__base.html' %}

{% block title %}
    Formulario 2 de reporte
{% endblock title %}

{% block content %}

<h3>Indica el avance de la actividad:</h3>
<p>El avance que hubo durante el periodo del reporte</p>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Agregar">
</form>

{% endblock content %}